"use client";

import { useState } from "react";
import { themes } from "@/lib/config/themes";
import type { Theme } from "@/lib/config/site";
import { Check, Copy, Download } from "lucide-react";

interface ConfigValues {
  // Site
  siteName: string;
  siteTagline: string;
  siteDescription: string;
  
  // Contact
  contactEmail: string;
  contactPhone: string;
  
  // Social
  socialTwitter: string;
  socialFacebook: string;
  socialInstagram: string;
  
  // Theme
  theme: Theme;
  
  // Currency
  currencyCode: string;
  currencySymbol: string;
  currencyLocale: string;
  
  // Shipping
  shippingFlatRate: string;
  freeShippingThreshold: string;
  
  // Supabase
  supabaseUrl: string;
  supabaseAnonKey: string;
  supabaseServiceKey: string;
  
  // Yoco (customer payments)
  yocoSecretKey: string;
  yocoPublicKey: string;
  yocoWebhookSecret: string;
  
  // PayFast (for subscriptions - SA market)
  payfastMerchantId: string;
  payfastMerchantKey: string;
  payfastPassphrase: string;
  payfastTestMode: boolean;
}

const defaultValues: ConfigValues = {
  siteName: "My Store",
  siteTagline: "Quality products, delivered fast",
  siteDescription: "Your one-stop shop for quality products",
  contactEmail: "",
  contactPhone: "",
  socialTwitter: "",
  socialFacebook: "",
  socialInstagram: "",
  theme: "default",
  currencyCode: "ZAR",
  currencySymbol: "R",
  currencyLocale: "en-ZA",
  shippingFlatRate: "60.00",
  freeShippingThreshold: "",
  supabaseUrl: "",
  supabaseAnonKey: "",
  supabaseServiceKey: "",
  yocoSecretKey: "",
  yocoPublicKey: "",
  yocoWebhookSecret: "",
  payfastMerchantId: "",
  payfastMerchantKey: "",
  payfastPassphrase: "",
  payfastTestMode: true,
};

export default function SetupPage() {
  const [values, setValues] = useState<ConfigValues>(defaultValues);
  const [copied, setCopied] = useState(false);
  const [activeSection, setActiveSection] = useState<string>("branding");

  function updateValue<K extends keyof ConfigValues>(key: K, value: ConfigValues[K]) {
    setValues((prev) => ({ ...prev, [key]: value }));
  }

  function generateEnvFile(): string {
    const shippingCents = Math.round(parseFloat(values.shippingFlatRate || "0") * 100);
    const freeShippingCents = values.freeShippingThreshold 
      ? Math.round(parseFloat(values.freeShippingThreshold) * 100) 
      : "";

    return `# ============================================
# SITE CONFIGURATION
# Generated by Setup Wizard
# ============================================

# Branding
NEXT_PUBLIC_SITE_NAME="${values.siteName}"
NEXT_PUBLIC_SITE_TAGLINE="${values.siteTagline}"
NEXT_PUBLIC_SITE_DESCRIPTION="${values.siteDescription}"

# Contact
NEXT_PUBLIC_CONTACT_EMAIL="${values.contactEmail}"
NEXT_PUBLIC_CONTACT_PHONE="${values.contactPhone}"

# Social Media
NEXT_PUBLIC_SOCIAL_TWITTER="${values.socialTwitter}"
NEXT_PUBLIC_SOCIAL_FACEBOOK="${values.socialFacebook}"
NEXT_PUBLIC_SOCIAL_INSTAGRAM="${values.socialInstagram}"

# Theme (options: default, luxury, minimal, vibrant, natural)
NEXT_PUBLIC_THEME="${values.theme}"

# Currency
NEXT_PUBLIC_CURRENCY_CODE="${values.currencyCode}"
NEXT_PUBLIC_CURRENCY_SYMBOL="${values.currencySymbol}"
NEXT_PUBLIC_CURRENCY_LOCALE="${values.currencyLocale}"

# Shipping (in cents)
NEXT_PUBLIC_SHIPPING_FLAT_RATE_CENTS="${shippingCents}"
${freeShippingCents ? `NEXT_PUBLIC_FREE_SHIPPING_THRESHOLD_CENTS="${freeShippingCents}"` : "# NEXT_PUBLIC_FREE_SHIPPING_THRESHOLD_CENTS="}

# Features
NEXT_PUBLIC_FEATURE_GUEST_CHECKOUT="true"
NEXT_PUBLIC_FEATURE_REVIEWS="false"
NEXT_PUBLIC_FEATURE_WISHLIST="false"

# Announcement Bar
NEXT_PUBLIC_ANNOUNCEMENT_ENABLED="true"
NEXT_PUBLIC_ANNOUNCEMENT_TEXT="Great products. Great deals. Delivered fast."
NEXT_PUBLIC_ANNOUNCEMENT_BADGE="HOT"

# ============================================
# SUPABASE (Database & Auth)
# Get these from: https://supabase.com/dashboard
# ============================================
NEXT_PUBLIC_SUPABASE_URL="${values.supabaseUrl}"
NEXT_PUBLIC_SUPABASE_ANON_KEY="${values.supabaseAnonKey}"
SUPABASE_SERVICE_ROLE_KEY="${values.supabaseServiceKey}"

# ============================================
# YOCO (Payment Processing)
# Get these from: https://developer.yoco.com
# ============================================
YOCO_SECRET_KEY="${values.yocoSecretKey}"
NEXT_PUBLIC_YOCO_PUBLIC_KEY="${values.yocoPublicKey}"
YOCO_WEBHOOK_SECRET="${values.yocoWebhookSecret}"

# ============================================
# PAYFAST (Subscription Billing - SA Market)
# Get these from: https://www.payfast.co.za/dashboard
# ============================================
PAYFAST_MERCHANT_ID="${values.payfastMerchantId}"
PAYFAST_MERCHANT_KEY="${values.payfastMerchantKey}"
PAYFAST_PASSPHRASE="${values.payfastPassphrase}"
PAYFAST_TEST_MODE="${values.payfastTestMode}"

# ============================================
# APP URL (Update for production)
# ============================================
NEXT_PUBLIC_APP_URL="http://localhost:3000"
`;
  }

  function copyToClipboard() {
    navigator.clipboard.writeText(generateEnvFile());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  function downloadEnvFile() {
    const blob = new Blob([generateEnvFile()], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = ".env.local";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }

  const sections = [
    { id: "branding", label: "Branding" },
    { id: "contact", label: "Contact" },
    { id: "theme", label: "Theme" },
    { id: "currency", label: "Currency" },
    { id: "shipping", label: "Shipping" },
    { id: "supabase", label: "Supabase" },
    { id: "yoco", label: "Yoco" },
    { id: "payfast", label: "PayFast" },
  ];

  return (
    <main className="min-h-screen bg-zinc-50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="text-center">
          <h1 className="text-3xl font-bold tracking-tight">Store Setup Wizard</h1>
          <p className="mt-2 text-zinc-600">
            Configure your store settings and generate your environment file
          </p>
        </div>

        <div className="mt-10 grid grid-cols-1 gap-8 lg:grid-cols-12">
          {/* Sidebar */}
          <div className="lg:col-span-3">
            <nav className="sticky top-6 space-y-1">
              {sections.map((section) => (
                <button
                  key={section.id}
                  onClick={() => setActiveSection(section.id)}
                  className={`w-full rounded-lg px-4 py-2 text-left text-sm transition ${
                    activeSection === section.id
                      ? "bg-black text-white"
                      : "hover:bg-zinc-100"
                  }`}
                >
                  {section.label}
                </button>
              ))}
            </nav>
          </div>

          {/* Main content */}
          <div className="lg:col-span-6">
            <div className="rounded-2xl border bg-white p-6 shadow-sm">
              {/* Branding */}
              {activeSection === "branding" && (
                <section>
                  <h2 className="text-lg font-semibold">Branding</h2>
                  <p className="mt-1 text-sm text-zinc-600">Your store name and description</p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Store Name</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.siteName}
                        onChange={(e) => updateValue("siteName", e.target.value)}
                        placeholder="My Awesome Store"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Tagline</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.siteTagline}
                        onChange={(e) => updateValue("siteTagline", e.target.value)}
                        placeholder="Quality products, delivered fast"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Description</label>
                      <textarea
                        className="mt-1 min-h-20 w-full rounded-md border px-3 py-2 text-sm"
                        value={values.siteDescription}
                        onChange={(e) => updateValue("siteDescription", e.target.value)}
                        placeholder="A brief description of your store for SEO"
                      />
                    </div>
                  </div>
                </section>
              )}

              {/* Contact */}
              {activeSection === "contact" && (
                <section>
                  <h2 className="text-lg font-semibold">Contact Information</h2>
                  <p className="mt-1 text-sm text-zinc-600">How customers can reach you</p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Email</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        type="email"
                        value={values.contactEmail}
                        onChange={(e) => updateValue("contactEmail", e.target.value)}
                        placeholder="hello@yourstore.com"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Phone</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.contactPhone}
                        onChange={(e) => updateValue("contactPhone", e.target.value)}
                        placeholder="+27 12 345 6789"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Twitter URL</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.socialTwitter}
                        onChange={(e) => updateValue("socialTwitter", e.target.value)}
                        placeholder="https://twitter.com/yourstore"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Facebook URL</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.socialFacebook}
                        onChange={(e) => updateValue("socialFacebook", e.target.value)}
                        placeholder="https://facebook.com/yourstore"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Instagram URL</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.socialInstagram}
                        onChange={(e) => updateValue("socialInstagram", e.target.value)}
                        placeholder="https://instagram.com/yourstore"
                      />
                    </div>
                  </div>
                </section>
              )}

              {/* Theme */}
              {activeSection === "theme" && (
                <section>
                  <h2 className="text-lg font-semibold">Theme Selection</h2>
                  <p className="mt-1 text-sm text-zinc-600">Choose a visual style for your store</p>
                  
                  <div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2">
                    {(Object.keys(themes) as Theme[]).map((themeKey) => {
                      const theme = themes[themeKey];
                      const isSelected = values.theme === themeKey;
                      
                      return (
                        <button
                          key={themeKey}
                          onClick={() => updateValue("theme", themeKey)}
                          className={`rounded-xl border-2 p-4 text-left transition ${
                            isSelected ? "border-black" : "border-zinc-200 hover:border-zinc-300"
                          }`}
                        >
                          <div className="flex items-center gap-2">
                            <div
                              className="h-6 w-6 rounded-full"
                              style={{ backgroundColor: theme.colors.primary }}
                            />
                            <div
                              className="h-6 w-6 rounded-full"
                              style={{ backgroundColor: theme.colors.accent }}
                            />
                            <div
                              className="h-6 w-6 rounded-full border"
                              style={{ backgroundColor: theme.colors.background }}
                            />
                          </div>
                          <div className="mt-3 font-medium">{theme.name}</div>
                          <div className="mt-1 text-xs text-zinc-600">{theme.description}</div>
                          {isSelected && (
                            <div className="mt-2 flex items-center gap-1 text-xs font-medium text-green-600">
                              <Check className="h-3 w-3" /> Selected
                            </div>
                          )}
                        </button>
                      );
                    })}
                  </div>
                </section>
              )}

              {/* Currency */}
              {activeSection === "currency" && (
                <section>
                  <h2 className="text-lg font-semibold">Currency Settings</h2>
                  <p className="mt-1 text-sm text-zinc-600">Configure your store currency</p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Currency Code</label>
                      <select
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.currencyCode}
                        onChange={(e) => {
                          const code = e.target.value;
                          updateValue("currencyCode", code);
                          if (code === "ZAR") {
                            updateValue("currencySymbol", "R");
                            updateValue("currencyLocale", "en-ZA");
                          } else if (code === "USD") {
                            updateValue("currencySymbol", "$");
                            updateValue("currencyLocale", "en-US");
                          } else if (code === "EUR") {
                            updateValue("currencySymbol", "€");
                            updateValue("currencyLocale", "en-EU");
                          } else if (code === "GBP") {
                            updateValue("currencySymbol", "£");
                            updateValue("currencyLocale", "en-GB");
                          }
                        }}
                      >
                        <option value="ZAR">ZAR - South African Rand</option>
                        <option value="USD">USD - US Dollar</option>
                        <option value="EUR">EUR - Euro</option>
                        <option value="GBP">GBP - British Pound</option>
                      </select>
                    </div>
                    <div>
                      <label className="text-sm font-medium">Currency Symbol</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        value={values.currencySymbol}
                        onChange={(e) => updateValue("currencySymbol", e.target.value)}
                      />
                    </div>
                  </div>
                </section>
              )}

              {/* Shipping */}
              {activeSection === "shipping" && (
                <section>
                  <h2 className="text-lg font-semibold">Shipping Settings</h2>
                  <p className="mt-1 text-sm text-zinc-600">Configure shipping rates</p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Flat Rate Shipping ({values.currencySymbol})</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        type="number"
                        step="0.01"
                        value={values.shippingFlatRate}
                        onChange={(e) => updateValue("shippingFlatRate", e.target.value)}
                        placeholder="99.00"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Free Shipping Threshold ({values.currencySymbol})</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm"
                        type="number"
                        step="0.01"
                        value={values.freeShippingThreshold}
                        onChange={(e) => updateValue("freeShippingThreshold", e.target.value)}
                        placeholder="Leave empty to disable"
                      />
                      <p className="mt-1 text-xs text-zinc-500">Leave empty to always charge shipping</p>
                    </div>
                  </div>
                </section>
              )}

              {/* Supabase */}
              {activeSection === "supabase" && (
                <section>
                  <h2 className="text-lg font-semibold">Supabase Configuration</h2>
                  <p className="mt-1 text-sm text-zinc-600">
                    Database and authentication settings.{" "}
                    <a href="https://supabase.com/dashboard" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">
                      Get these from Supabase Dashboard
                    </a>
                  </p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Project URL</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        value={values.supabaseUrl}
                        onChange={(e) => updateValue("supabaseUrl", e.target.value)}
                        placeholder="https://xxxxx.supabase.co"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Anon Key (public)</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        value={values.supabaseAnonKey}
                        onChange={(e) => updateValue("supabaseAnonKey", e.target.value)}
                        placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6..."
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Service Role Key (secret)</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        type="password"
                        value={values.supabaseServiceKey}
                        onChange={(e) => updateValue("supabaseServiceKey", e.target.value)}
                        placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6..."
                      />
                      <p className="mt-1 text-xs text-red-600">Keep this secret! Never expose in client code.</p>
                    </div>
                  </div>
                </section>
              )}

              {/* Yoco */}
              {activeSection === "yoco" && (
                <section>
                  <h2 className="text-lg font-semibold">Yoco Payment Gateway</h2>
                  <p className="mt-1 text-sm text-zinc-600">
                    For processing customer payments.{" "}
                    <a href="https://developer.yoco.com" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">
                      Get these from Yoco Developer Portal
                    </a>
                  </p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Secret Key</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        type="password"
                        value={values.yocoSecretKey}
                        onChange={(e) => updateValue("yocoSecretKey", e.target.value)}
                        placeholder="sk_live_..."
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Public Key</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        value={values.yocoPublicKey}
                        onChange={(e) => updateValue("yocoPublicKey", e.target.value)}
                        placeholder="pk_live_..."
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Webhook Secret</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        type="password"
                        value={values.yocoWebhookSecret}
                        onChange={(e) => updateValue("yocoWebhookSecret", e.target.value)}
                        placeholder="whsec_..."
                      />
                    </div>
                  </div>
                </section>
              )}

              {/* PayFast */}
              {activeSection === "payfast" && (
                <section>
                  <h2 className="text-lg font-semibold">PayFast Subscription Billing</h2>
                  <p className="mt-1 text-sm text-zinc-600">
                    For charging clients monthly (SA market).{" "}
                    <a href="https://www.payfast.co.za/dashboard" target="_blank" rel="noreferrer" className="text-blue-600 hover:underline">
                      Get these from PayFast Dashboard
                    </a>
                  </p>
                  
                  <div className="mt-6 space-y-4">
                    <div>
                      <label className="text-sm font-medium">Merchant ID</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        value={values.payfastMerchantId}
                        onChange={(e) => updateValue("payfastMerchantId", e.target.value)}
                        placeholder="10000100"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Merchant Key</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        type="password"
                        value={values.payfastMerchantKey}
                        onChange={(e) => updateValue("payfastMerchantKey", e.target.value)}
                        placeholder="46f0cd694581a"
                      />
                    </div>
                    <div>
                      <label className="text-sm font-medium">Passphrase (optional)</label>
                      <input
                        className="mt-1 h-10 w-full rounded-md border px-3 text-sm font-mono"
                        type="password"
                        value={values.payfastPassphrase}
                        onChange={(e) => updateValue("payfastPassphrase", e.target.value)}
                        placeholder="Your passphrase"
                      />
                      <p className="mt-1 text-xs text-zinc-500">Set in PayFast dashboard under Settings → Integration</p>
                    </div>
                    <div>
                      <label className="flex items-center gap-2 text-sm">
                        <input
                          type="checkbox"
                          checked={values.payfastTestMode}
                          onChange={(e) => updateValue("payfastTestMode", e.target.checked)}
                        />
                        <span className="font-medium">Test Mode (Sandbox)</span>
                      </label>
                      <p className="mt-1 text-xs text-zinc-500">Enable for testing, disable for live payments</p>
                    </div>
                  </div>
                </section>
              )}

              {/* Navigation */}
              <div className="mt-8 flex justify-between border-t pt-6">
                <button
                  onClick={() => {
                    const idx = sections.findIndex((s) => s.id === activeSection);
                    if (idx > 0) setActiveSection(sections[idx - 1].id);
                  }}
                  disabled={activeSection === sections[0].id}
                  className="rounded-md border px-4 py-2 text-sm disabled:opacity-50"
                >
                  Previous
                </button>
                <button
                  onClick={() => {
                    const idx = sections.findIndex((s) => s.id === activeSection);
                    if (idx < sections.length - 1) setActiveSection(sections[idx + 1].id);
                  }}
                  disabled={activeSection === sections[sections.length - 1].id}
                  className="rounded-md bg-black px-4 py-2 text-sm text-white disabled:opacity-50"
                >
                  Next
                </button>
              </div>
            </div>
          </div>

          {/* Preview / Output */}
          <div className="lg:col-span-3">
            <div className="sticky top-6 space-y-4">
              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <h3 className="font-medium">Generated .env.local</h3>
                <p className="mt-1 text-xs text-zinc-600">
                  Download or copy this file to your project root
                </p>
                
                <div className="mt-4 flex gap-2">
                  <button
                    onClick={downloadEnvFile}
                    className="flex flex-1 items-center justify-center gap-2 rounded-md bg-black px-4 py-2 text-sm text-white"
                  >
                    <Download className="h-4 w-4" />
                    Download
                  </button>
                  <button
                    onClick={copyToClipboard}
                    className="flex items-center justify-center gap-2 rounded-md border px-4 py-2 text-sm"
                  >
                    {copied ? <Check className="h-4 w-4 text-green-600" /> : <Copy className="h-4 w-4" />}
                  </button>
                </div>
              </div>

              <div className="rounded-2xl border bg-white p-4 shadow-sm">
                <h3 className="font-medium">Setup Steps</h3>
                <ol className="mt-3 space-y-2 text-sm text-zinc-600">
                  <li className="flex gap-2">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-medium">1</span>
                    <span>Fill in all configuration fields</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-medium">2</span>
                    <span>Download the .env.local file</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-medium">3</span>
                    <span>Place it in your project root</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-medium">4</span>
                    <span>Run Supabase migrations</span>
                  </li>
                  <li className="flex gap-2">
                    <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full bg-zinc-100 text-xs font-medium">5</span>
                    <span>Restart the dev server</span>
                  </li>
                </ol>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
